Controllers/EJAddTranProbTermController.cs
using K4os.Compression.LZ4.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using MySql.Data.MySqlClient;
using Mysqlx;
using OfficeOpenXml;
using PagedList;
using SLA_Management.Commons;
using SLA_Management.Data;
using SLA_Management.Data;
using SLA_Management.Data.ExcelUtilitie;
using SLA_Management.Data.HealthCheck;
using SLA_Management.Data.TermProb;
using SLA_Management.Models;
using SLA_Management.Models.ManagementModel;
using SLA_Management.Models.OperationModel;
using SLA_Management.Models.TermProbModel;
using System;
using System.Data;
using System.Data.Common;
using System.Drawing;
using System.Globalization;


namespace SLA_Management.Controllers
{
    public class EJAddTranProbTermController : Controller
    {

        #region Local Variable
        private CultureInfo _cultureEnInfo = new CultureInfo("en-US");
        private static List<ej_trandeviceprob> ejLog_dataList = new List<ej_trandeviceprob>();
        private static ej_trandada_seek param = new ej_trandada_seek();
        private IConfiguration _myConfiguration;
        private DBService_TermProb dBService;


        #endregion

        #region Constructor

        public EJAddTranProbTermController(IConfiguration myConfiguration)
        {
            _myConfiguration = myConfiguration;

        }

        #endregion

        #region Action page

        public IActionResult EJAddTranProbTermAction(string cmdButton, string TermID, string FrDate, string ToDate, string FrTime, string ToTime
        , string currTID, string currFr, string currTo, string currFrTime, string currToTime, string lstPageSize
        , string ddlProbMaster, string currProbMaster, string MessErrKeyWord, string currMessErrKeyWord
        , string currPageSize, int? page, string maxRows, string KeyWordList, string terminalType, string startDate, string bankName)
        {

            List<ej_trandeviceprob> recordset = new List<ej_trandeviceprob>();
            List<ProblemMaster> ProdMasData = new List<ProblemMaster>();
            List<ProblemMaster> ProdAllMasData = new List<ProblemMaster>();

            DBService_TermProb dBService;

            bool noBankSelect = false;

            //if (bankName == null) bankName = "BAAC";

            switch (bankName)
            {
                case "BAAC":
                    dBService = new DBService_TermProb(_myConfiguration, _myConfiguration.GetValue<string>("ConnectString_NonOutsource:FullNameConnection_baac"));
                    break;
                case "ICBC":
                    dBService = new DBService_TermProb(_myConfiguration, _myConfiguration.GetValue<string>("ConnectString_NonOutsource:FullNameConnection_icbc"));
                    break;
                case "BOC":
                    dBService = new DBService_TermProb(_myConfiguration, _myConfiguration.GetValue<string>("ConnectString_NonOutsource:FullNameConnection_boct"));
                    break;
                default:
                    noBankSelect = true;
                    dBService = new DBService_TermProb(_myConfiguration);
                    break;
            }

            SetLatestUpdateViewBag(bankName);

            //if (terminalType == "ADM") terminalType = "G262";
            //else if (terminalType == "ATM") terminalType = "G165";
            //else if (terminalType == "All") terminalType = "G165;G262";

            if (startDate == null || startDate == "")
                startDate = DateTime.Now.ToString("yyyy-MM-dd");

            ViewBag.startDate = startDate;


            string[] strErrorWordSeparate = _myConfiguration.GetValue<string>("KeyWordSeparate").ToUpper().Split(',');

            ejLog_dataList.Clear();

            int pageNum = 1;
            try
            {


                if (cmdButton == "Clear")
                    return RedirectToAction("EJAddTranProbTermAction");


                #region Set viewBag and default data
                if (null == TermID && null == FrDate && null == ToDate && null == page)
                {

                    FrDate = DateTime.Now.ToString("yyyy-MM-dd", _cultureEnInfo);
                    ToDate = DateTime.Now.ToString("yyyy-MM-dd", _cultureEnInfo);
                    page = 1;
                }
                else
                {
                    // Return temp value back to it own variable
                    FrDate = (FrDate ?? currFr);
                    ToDate = (ToDate ?? currTo);
                    FrTime = (FrTime ?? currFrTime);
                    ToTime = (ToTime ?? currToTime);
                    TermID = (TermID ?? currTID);
                    ddlProbMaster = (ddlProbMaster ?? currProbMaster);
                    MessErrKeyWord = (MessErrKeyWord ?? currMessErrKeyWord);
                }

                if (DBService.CheckDatabase())
                {
                    ProdMasData = dBService.GetMasterSysErrorWord();
                    ProdAllMasData = dBService.GetAllMasterSysErrorWord();

                    List<string> list = ProdAllMasData.Select(p => p.ProbType).Distinct().ToList();

                    ViewBag.probTypeStr = new SelectList(list);

                    ViewBag.ConnectDB = "true";
                }
                else
                {
                    ViewBag.ConnectDB = "false";
                }


                if (ProdMasData.Count > 0)
                {
                    ViewBag.ProbMaster = "";
                    string strTemp = string.Empty;
                    foreach (ProblemMaster obj in ProdMasData)
                    {
                        strTemp = "";
                        if (ViewBag.ProbMaster == "")
                        {
                            //if (obj.ProblemName.Length > 65)
                            //{
                            //    strTemp = obj.ProblemCode + "$" + obj.ProblemName;
                            //}
                            //else
                            //{
                            //    strTemp = obj.ProblemCode + "$" + obj.ProblemName + " : " + obj.Memo;

                            //}

                            //if (strTemp.Length > 65) strTemp = obj.ProblemCode + "$" + obj.ProblemName;
                            strTemp = obj.ProblemCode + "$" + obj.Memo + " : " + obj.ProblemName;
                        }
                        else
                        {
                            //if (obj.ProblemName.Length > 65)
                            //{
                            //    strTemp = "|" + obj.ProblemCode + "$" + obj.ProblemName;
                            //}
                            //else
                            //{
                            //    strTemp = "|" + obj.ProblemCode + "$" + obj.ProblemName + " : " + obj.Memo;


                            //}
                            //if (strTemp.Length > 65) strTemp = "|" + obj.ProblemCode + "$" + obj.ProblemName;

                            strTemp = "|" + obj.ProblemCode + "$" + obj.Memo + " : " + obj.ProblemName;
                        }

                        if (strTemp != null && strTemp != string.Empty)
                            ViewBag.ProbMaster += strTemp;

                    }
                }

                List<Device_info_record> device_Info_Records = new List<Device_info_record>();

                if (!noBankSelect)
                {
                    device_Info_Records = dBService.GetDeviceInfoFeelview();

                }



                var additionalItems = device_Info_Records.Select(x => x.TYPE_ID).Distinct();
                if (bankName == "BAAC")
                {
                    additionalItems = device_Info_Records.Select(x => x.COUNTER_CODE).Distinct();
                }

                var item = new List<string> { "All" };


                ViewBag.probTermStr = new SelectList(additionalItems.Concat(item).ToList());


                ViewBag.CurrentTID = device_Info_Records;
                ViewBag.TermID = TermID;
                ViewBag.CurrentFr = (FrDate ?? currFr);
                ViewBag.CurrentTo = (ToDate ?? currTo);
                ViewBag.CurrentPageSize = (lstPageSize ?? currPageSize);
                //ViewBag.CurrentProbMaster = ddlProbMaster == null ? currProbMaster : ddlProbMaster;
                ViewBag.CurrentProbMaster = KeyWordList;
                ViewBag.CurrentMessErrKeyWord = MessErrKeyWord == null ? currMessErrKeyWord : MessErrKeyWord;
                #endregion


                #region Set param
                bool chk_date = false;
                if (null == TermID)
                    param.TERMID = currTID == null ? "" : currTID;
                else
                    param.TERMID = TermID == null ? "" : TermID;

                if ((FrDate == null && currFr == null) && (FrDate == "" && currFr == ""))
                {
                    param.FRDATE = DateTime.Now.ToString("yyyy-MM-dd") + " 00:00:00";
                    chk_date = false;
                }
                else
                {
                    if ((FrTime == "" && currFrTime == "") || (FrTime == null && currFrTime == null) ||
                        (FrTime == null && currFrTime == "") || (FrTime == "" && currFrTime == null))
                        param.FRDATE = FrDate + " 00:00:00";
                    else
                        param.FRDATE = FrDate + " " + FrTime;
                    chk_date = true;
                }

                if ((ToDate == null && currTo == null) && (ToDate == "" && currTo == ""))
                {
                    param.TODATE = DateTime.Now.ToString("yyyy-MM-dd") + " 23:59:59";
                }
                else
                {
                    if ((ToTime == "" && currToTime == "") || (ToTime == null && currToTime == null) ||
                        (ToTime == null && currToTime == "") || (ToTime == "" && currToTime == null))

Views/Shared/Login.cshtml
@model SLA_Management.Models.LoginModel

@{
    ViewBag.Title = "Operation Management - Login";
    Layout = "~/Views/Shared/_Layout_Login.cshtml";
}



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>


        .login-wrapper {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: calc(100vh - 120px); 
            padding: 60px 0;
        }

        .login-container {
            display: flex;
            width: 90vw;
            max-width: 1400px;
            height: 600px;
            background: white;
            border-radius: 16px;
            box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.2);
            overflow: hidden;
        }

       
        .login-left {
            flex: 1;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: flex-end;
            padding: 20px;
            background: #ffe0b2;
        }

        .welcome-image {
            width: 100%;
            max-width: 447px;
            height: auto;
        }

        .computer-image {
            width: 100%;
            max-width: 33vw;
            height: auto;
        }


       
        .login-right {
            flex: 1;
            padding: 50px;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }

            .login-right h2 {
                text-align: center;
                margin-bottom: 30px;
                font-weight: bold;
                font-size: 28px;
            }

        .form-group {
            margin-bottom: 20px;
        }

        .btn-group {
            display: flex;
            justify-content: space-between;
        }


    </style>
</head>


<div class="login-wrapper">
    <div class="login-container">
        <!-- left -->
        <div class="login-left">
            <div id="row-pic-welcome" class="row">
                <div class="col-12">
                    <img src="~/images/Pic_Welcome.png" alt="Welcome Image" class="welcome-image">
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <img src="~/images/PIC_Computer.png" alt="Computer Image" class="computer-image">
                </div>
            </div>
        </div>


        <!-- right -->
        <div class="login-right">
            <h2>Operation Management</h2>
            @using (Html.BeginForm("Login", "LoginMain", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
               

                <div class="form-group">
                    @Html.LabelFor(m => m.Username, new { @class = "form-label" })
                    @Html.TextBoxFor(m => m.Username, new { @class = "form-control", placeholder = "Enter your username" })
                    @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "form-label" })
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Enter your password" })
                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                </div>

                <div class="btn-group">
                    <button type="submit" class="btn btn-warning">Login</button>
                    <a href="@Url.Action("Login", "LoginMain")" class="btn btn-secondary">Cancel</a>
                </div>

                @Html.ValidationSummary(true, "", new { @class = "text-danger mb-3" })
            }
        </div>
    </div>
</div>
@if (TempData["Error"] != null)
{
    <script>
        alert(@Html.Raw(Json.Serialize(TempData["Error"])));
    </script>
}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Operation</title>
       <!-- Style -->
   @* <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/MainCSS_gateway.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SLA_Management.styles.css" asp-append-version="true" />
    <link rel="shortcut icon" href="~/images/favicon.ico" type="image/x-icon"/>
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>*@
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/MainCSS_gateway.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="shortcut icon" href="~/images/favicon.ico" type="image/x-icon" />

    <link href="~/lib/bootstrap-select.1.13.18/content/content/bootstrap-select.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-select.1.13.18/content/content/bootstrap-select.min.css" rel="stylesheet" />

    <link href="~/lib/bootstrap-select.1.13.18/css/bootstrap-select.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SLA_Management.styles.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/popper.js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap-select.1.13.18/js/bootstrap-select.js"></script>
</head>
@{
    string selectHeader = "";
    string forcss_header = "";
    selectHeader = @ViewData["Title"].ToString();
    switch (selectHeader)
    {
        case "Home Page":
            forcss_header = "home";
            break;
        case "Cash Report":
            forcss_header = "report";
            break;
        case "Log File Monitor":
            forcss_header = "log";
            break;
        case "Problem Management":
            forcss_header = "monitor";
            break;
        default:
            break;
    }
}
<style>
  li:hover{
        /*border-radius: 0px 0px 30px 0px;*/
        background-color: rgba(30,30,30,0.14);
    }
    .navbar {
            padding-top: 0px;
            padding-bottom: 0px;
            border: 0;
            border-radius: 0;
            margin-bottom: 0;
            font-size: 1rem;
            letter-spacing: 1px;
        background: rgb(238,168,73);
        background: linear-gradient(90deg, rgba(238,168,73,1) 0%, rgba(244,107,69,1) 100%);
    }
    .navbar a:hover, .dropdown:hover .dropbtn {
            background-color: rgba(244,107,69,1) 100%);
    }
    .nav-link{
            padding: 1rem 1rem;
    }

    .bg_home {
       background-image: url('/Operation/images/Pic_Page.png');
        background-size: 100% 100%;
        background-position: top;
        background-repeat: no-repeat;
    }
    .bg_main{
    }
    .nav-item{
        width: auto;    
        text-align: center;
        padding: 0px 15px 0px 15px;
    }
    .nav-@forcss_header{
        border-radius: 0px 0px 30px 0px;
        background-color: rgba(30,30,30,0.14);
    }
    @@media (max-width: 1199px) {
        .footer-left {
            justify-content: center;
            padding: 0;
        }
        .footer-right{
            justify-content: center;
            padding: 0;
        }
        footer{
            line-height: 20px;
        }
    }
    @@media (min-width: 1200px) { 
        .footer-left {
            justify-content: flex-end;
            padding: 0px 40px 0px 0px;
        }
        .footer-right{
            justify-content: flex-start;
            padding: 0px 0px 0px 40px;
        }
        footer{
            line-height: 40px;
        }
    }
</style>
@{
    string urlBG = "";
    if (ViewData["Title"] == "Home Page")
    {
        urlBG = "bg_home";
    }
    else
    {
        urlBG = "bg_main";
    }
}

@*<img src="~/images/Pic_Home.png" alt="Logo" align="right" style="height:auto;width:100%;max-width:790px; display:none;">
<img src="~/images/Pic_Page.png" alt="Logo" align="right" style="height:auto;width:100%;max-width:790px; display:none;">*@
@*url('/Operation/images/Pic_Home.png');*@
@*'../images/Pic_Home.png'*@
<body class="bg_main bg_home" style="background-image: url('/Operation/images/Pic_Page.png');background-size:100% auto">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  box-shadow mb-3">
            <div class="container-fluid">
                <div>
                     <img src="~/images/2.png" width="127" height="53" alt="Logo" align="left" style="padding-right:30px;" >
                </div>
                
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SLA Management</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item nav-home">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                Monitor
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="EJAddTranProbTerm" asp-action="EJAddTranProbTermAction">Problem Monitor</a>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Operation" asp-action="Transactions">Transaction Monitor</a>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Operation" asp-action="AdminCardMonitor">Admin Card Monitor</a>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Operation" asp-action="LastTransaction">Last Transaction Monitor</a>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Operation" asp-action="CardRetain">Card Retain Monitor</a>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Monitor" asp-action="CavityNoteMonitor">Cavity Note Monitor</a>
                               @* <a class="dropdown-item text-dark" asp-area="" asp-controller="Gateway" asp-action="Transaction">Gateway Transaction</a>*@
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                Report
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Report" asp-action="BalancingReport">Balancing Report</a>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Report" asp-action="InventoryMonitorHistory">Inventory Report History</a>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Operation" asp-action="Regulator">Cash Report(รายงานข้อมูลฝาก-ถอน)</a>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Report" asp-action="HardwareReport">Hardware Report</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown nav-log">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                Log Management
                            </a>
                            <div class="dropdown-menu">
                                @*<a class="dropdown-item text-dark" asp-area="" asp-controller="Operation" asp-action="CheckEJSize">Check EJ Size(POC)</a>*@
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Operation" asp-action="CheckEJLastUpdate">Log File Monitor</a>
                                @*<a class="dropdown-item text-dark" asp-area="" asp-controller="ComlogNew" asp-action="Index">COM Log Management</a>*@
                            </div>
                        </li>
                        @*  <li class="nav-item dropdown nav-report">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                Report
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Operation" asp-action="Regulator">Cash Report(รายงานข้อมูลฝาก-ถอน)</a>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Operation" asp-action="TicketManagement">Ticket Management</a>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Operation" asp-action="SlaTracking">SLA Tracking(POC)</a>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Operation" asp-action="SlaReportDaily">SLA Report Daily(POC)</a>
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Operation" asp-action="SlaReportMonthly">SLA Report Monthly(POC)</a>
                                
                            </div>
                        </li> *@              
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                Manangement
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item text-dark" asp-area="" asp-controller="Management" asp-action="InventoryMonitor">Inventory Management</a>

                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>  
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:orange;">
        <div class="container-fluid">
        <div class="row fs-6" style="color:whitesmoke;">
            <div class="col-12 col-xl-4">
                <div class="row">
                        
                    <div class="footer-left" style="margin: 0px;display: flex;height: 2vh;">1023 MS Siam Tower, 30th Floor, Rama 3 Rd,</div>
                </div>
                <div class="row">
                    <div class="footer-left" style="margin: 0px;display: flex;">Chongnonsi, Yannawa, Bangkok, 10120 Thailand</div>
                </div>
            </div>
            <div class="col-12 col-xl-4">
                <div class="row">
                      <div class="footer-center" style="padding: 0px 0px 0px 0px;margin: 0px;display: flex;justify-content: center;height: 2vh;">Copyright© 2023 - Dataone Asia Co., Ltd</div>
                </div>
                <div class="row">
                      <div class="footer-center"  style="padding: 0px 0px 0px 0px;margin: 0px;display: flex;justify-content: center;height: 2vh;">Government Housing Bank</div>
                </div>
                <div class="row">
                      <div class="footer-center"  style="padding: 0px 0px 0px 0px;margin: 0px;display: flex;justify-content: center;">Version 1.0.1</div>
                </div>
            </div>
            <div class="col-12 col-xl-4">
                <div class="row">
                    <div class="footer-right" style="margin: 0px;display: flex;height: 2vh;">Tel: +66 2686 3000</div>
                </div>
                <div class="row">
                    <div class="footer-right" style="margin: 0px;display: flex;">Fax: +66 2682 6322, +66 2686 6468</div>
                </div>
            </div>
        </div>
        </div>
    </footer>
    <script>
        if("@ViewData["Title"]"==="Home Page"){
            document.addEventListener('DOMContentLoaded', function () {
                // Get the element with the class 'example-class'
                const element = document.querySelector('.bg_main');
                if (element) {
                    element.style.removeProperty('background-image');
                    element.style.removeProperty('background-size');
                }
            });
        }
        
    </script>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>