Models/CassetteStatus/CassetteBox.cs
namespace SLA_Management.Models.CassetteStatus
{
    public class CassetteBox
    {
        public string bc { get; set; }
        public string bec { get; set; }
        public string bd { get; set; }
        public string blm { get; set; }
        public string bln { get; set; }
        public string bdn { get; set; }
        public string ban { get; set; }
        public string blmc { get; set; }
        public string bs { get; set; }
        public string blnc { get; set; }
        public string bt { get; set; }
        public string bdt { get; set; }
        public string bid { get; set; }

    }
}

Models/CassetteStatus/CassetteEventFile.cs
namespace SLA_Management.Models.CassetteStatus
{
    public class CassetteEventFile
    {
        public string Id { get; set; }
        public string Name_File { get; set; }
        public string Upload_By { get; set; }
        public DateTime Upload_Date { get; set; }
        public DateTime Data_Date { get; set; }

    }
}

Models/CassetteStatus/DeviceInfo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SLA_Management.Models.CassetteStatus
{
    [Table("device_info")]
    public class DeviceInfo
    {
        [Key]
        public string DEVICE_ID { get; set; }
        public string TERM_ID { get; set; }
        public string DEPT_ID { get; set; }
        public string TYPE_ID { get; set; }
        public string BRAND_ID { get; set; }
        public string MODEL_ID { get; set; }
        public string TERM_SEQ { get; set; }
        public string COUNTER_CODE { get; set; }
        public string TERM_IP { get; set; }
        public string STATUS { get; set; }
        public string TERM_NAME { get; set; }
        public string TERM_ADDR { get; set; }
        public string TERM_LOCATION { get; set; }
        public string TERM_ZONE { get; set; }
        public string CONTROL_BY { get; set; }
        public string REPLENISH_BY { get; set; }
        public string POST { get; set; }
        public string INSTALL_DATE { get; set; }
        public string ACTIVE_DATE { get; set; }
        public string SERVICE_TYPE { get; set; }
        public string INSTALL_TYPE { get; set; }
        public string LAYOUT_TYPE { get; set; }
        public string MAN_ID { get; set; }
        public string SERVICEMAN_ID { get; set; }
        public string COMPANY_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string SERVICE_BEGINDATE { get; set; }
        public string SERVICE_ENDDATE { get; set; }
        public string SERVICE_YEARS { get; set; }
        public string IS_CCTV { get; set; }
        public string IS_UPS { get; set; }
        public string IS_INTERNATIONAL { get; set; }
        public string BUSINESS_BEGINTIME { get; set; }
        public string BUSINESS_ENDTIME { get; set; }
        public string IS_VIP { get; set; }
        public string AREA_ID { get; set; }
        public string AREA_ADDR { get; set; }
        public string FUNCTION_TYPE { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public string PROVINCE { get; set; }
        public string LOT_TYPE { get; set; }
        public string AUDITING { get; set; }
        public string CURRENT_IP { get; set; }
        public string VERSION_ATMC { get; set; }
        public string VERSION_SP { get; set; }
        public string VERSION_AGENT { get; set; }
        public string VERSION_MB { get; set; }
        public string FLAG_XFS { get; set; }
        public string FLAG_EJ { get; set; }
        public string FLAG_FSN { get; set; }
        public string EJ_FILES { get; set; }
        public string FSN_PATH { get; set; }
        public string TASK_PARA { get; set; }
        public string VERSION_AD { get; set; }
        public string MODIFY_USERID { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string ADD_USERID { get; set; }
        public DateTime? ADD_DATE { get; set; }
        public string ASSET_NO { get; set; }
        public string CASH_BOX_NUM { get; set; }
        public string SERVICE_SMS_TYPE { get; set; }
        public string EJ_OPEN_DATE { get; set; }
        public DateTime? ATMC_UPDATE_TIME { get; set; }
        public DateTime? SP_UPDATE_TIME { get; set; }
        public DateTime? AGENT_UPDATE_TIME { get; set; }
        public string VERSION_NV { get; set; }
        public DateTime? NV_UPDATE_TIME { get; set; }
        public string VERSION_MAIN { get; set; }
        public DateTime? MAIN_UPDATE_TIME { get; set; }
    }
}

Models/CassetteStatus/ImportFileData.cs
namespace SLA_Management.Models.CassetteStatus
{
    public class ImportFileData
    {
        public string Id { get; set; }
        public string Name_File { get; set; }
        public string Upload_By { get; set; }
        public DateTime Upload_Date { get; set; }
        public DateTime Data_Date { get; set; }
        public string Import_Data_Project { get; set; }

    }
}

Models/CassetteStatus/ReportCassette.cs
namespace SLA_Management.Models.CassetteStatus
{
    public class ReportCassette
    {
        public string cassetteId { get; set; }
        public int cassetteStatusCount { get; set; }
        public string fileData { get; set; }
        public string cassetteStatus { get; set; }

        public ReportCassette(string cassetteId, int cassetteStatusCount, string fileData, string cassetteStatus)
        {
            this.cassetteId = cassetteId;
            this.cassetteStatusCount = cassetteStatusCount;
            this.fileData = fileData;
            this.cassetteStatus = cassetteStatus;
        }
    }
}

Models/CassetteStatus/ReportCassetteDB.cs
namespace SLA_Management.Models.CassetteStatus
{
    public class ReportCassetteDB
    {
        public string Id { get; set; }
        public string Cassette_Id { get; set; }
        public int Cassette_Status_Count { get; set; }
        public string Cassette_Status { get; set; }
        public string Cassette_Event_File_Id { get; set; }

    }
}

Models/CassetteStatus/ReportTerminalCassette.cs
namespace SLA_Management.Models.CassetteStatus
{
    public class ReportTerminalCassette
    {
        public string termId { get; set; }
        public string cassetteId { get; set; }
        public string cassetteStatus { get; set; }
        public int cassetteRemain { get; set; }
        public string fileData { get; set; }


        public string CassetteDescription()
        {
            string result = cassetteStatus;

            switch (cassetteStatus)
            {
                case "0":
                    result = "Cassette Normal";
                    break;
                case "1":
                    result = "Cash Low";
                    break;
                case "2":
                    result = "Cash Out";
                    break;
                case "9":
                    result = "Cassette Fault";
                    break;
                default:
                    result = cassetteStatus;
                    break;
            }
            return result;
        }





    }
}

Models/CassetteStatus/ReportTerminalCassetteDB.cs
namespace SLA_Management.Models.CassetteStatus
{
    public class ReportTerminalCassetteDB
    {
        public string Id { get; set; }
        public string TermId { get; set; }
        public string Cassette_Id { get; set; }
        public string Cassette_Status { get; set; }
        public int Cassette_Remain { get; set; }
        public string Cassette_Event_File_Id { get; set; }



    }
}

Models/CassetteStatus/TerminalCassetteData.cs
namespace SLA_Management.Models.CassetteStatus
{
    public class TerminalCassetteData
    {
        public DateTime queryDate { get; set; }
        public List<TerminalCassette> data { get; set; }
    }
}

Controllers/ManagementController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MySql.Data.MySqlClient;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using SLA_Management.Commons;
using SLA_Management.Data;
using SLA_Management.Data.ExcelUtilitie;
using SLA_Management.Models.ManagementModel;
using SLA_Management.Models.OperationModel;
using SLA_Management.Models.ReportModel;
using SLA_Management.Models.TermProbModel;
using SLA_Management.Services;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using static Services.ReportCassetteBoxService;


namespace SLA_Management.Controllers
{
    public class ManagementController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly CassetteService _cassetteService;
        private readonly ReportCasesCheckService _reportCasesCheckService;

        private static regulator_seek param = new regulator_seek();
        private static List<TicketManagement> ticket_dataList = new List<TicketManagement>();
        private static List<TicketManagement> recordset_ticketManagement = new List<TicketManagement>();
        public ManagementController(IConfiguration configuration, CassetteService cassetteService, ReportCasesCheckService reportCaesCheckService)
        {
            _configuration = configuration;
            _cassetteService = cassetteService;
            _reportCasesCheckService = reportCaesCheckService;
        }

        private static List<Device_info_record> GetDeviceInfoFeelview(string _bank, IConfiguration _myConfiguration)
        {

            ConnectMySQL db_mysql = new ConnectMySQL(_myConfiguration.GetValue<string>("ConnectString_NonOutsource:FullNameConnection_" + _bank));
            MySqlCommand com = new MySqlCommand();
            com.CommandText = "SELECT * FROM device_info order by TERM_SEQ;";
            DataTable testss = db_mysql.GetDatatable(com);

            List<Device_info_record> test = ConvertDataTableToModel.ConvertDataTable<Device_info_record>(testss);

            return test;
        }
        public class IssueName
        {
            public string Issue_Name { get; set; }
        }
        private static List<IssueName> GetIssue_Name(string _bank, IConfiguration _myConfiguration)
        {
            ConnectMySQL db_mysql = new ConnectMySQL(_myConfiguration.GetValue<string>("ConnectString_NonOutsource:FullNameConnection_" + _bank));
            MySqlCommand com = new MySqlCommand();
            com.CommandText = "SELECT Issue_Name FROM reportcases  group by Issue_Name order by Issue_Name;";
            DataTable testss = db_mysql.GetDatatable(com);

            List<IssueName> test = ConvertDataTableToModel.ConvertDataTable<IssueName>(testss);

            return test;
        }
        public class StatusName
        {
            public string Status_Name { get; set; }
        }
        private static List<StatusName> GetStatus_Name(string _bank, IConfiguration _myConfiguration)
        {
            ConnectMySQL db_mysql = new ConnectMySQL(_myConfiguration.GetValue<string>("ConnectString_NonOutsource:FullNameConnection_" + _bank));
            MySqlCommand com = new MySqlCommand();
            com.CommandText = "SELECT Status_Name FROM reportcases  group by Status_Name order by Status_Name;";
            DataTable testss = db_mysql.GetDatatable(com);

            List<StatusName> test = ConvertDataTableToModel.ConvertDataTable<StatusName>(testss);

            return test;
        }

        #region Holiday
        public IActionResult Holiday()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetEvents()
        {
            List<object> eventsList = new List<object>();

            string connectionString = _configuration.GetConnectionString("DefaultConnection");

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string query = "SELECT Holiday as Title, CONVERT(DATE, Date) as StartDate FROM t_msd_Holiday";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            var title = reader["Title"].ToString();
                            var start = DateTime.Parse(reader["StartDate"].ToString()).ToString("yyyy-MM-dd");

                            eventsList.Add(new { title, start });
                        }
                    }
                }
            }


            return Json(eventsList);
        }
        [HttpPost]
        public IActionResult CreateEvent(string title, DateTime start, string user)
        {
            TimeZoneInfo thaiTimeZone = TimeZoneInfo.FindSystemTimeZoneById("SE Asia Standard Time");
            start = TimeZoneInfo.ConvertTimeFromUtc(start, thaiTimeZone);
            try
            {
                var connectionString = _configuration.GetConnectionString("DefaultConnection");
                using (var connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    var sqlCommand = new SqlCommand("INSERT INTO t_msd_Holiday (Date, Holiday,CreatedBy,CreatedDate,UpdatedDate) VALUES (@start, @title,@CreatedBy,@CreatedDate,@UpdatedDate)", connection);

                    sqlCommand.Parameters.AddWithValue("@start", start.Date);
                    sqlCommand.Parameters.AddWithValue("@title", title);
                    sqlCommand.Parameters.AddWithValue("@CreatedBy", user);
                    sqlCommand.Parameters.AddWithValue("@CreatedDate", DateTime.Now);
                    sqlCommand.Parameters.AddWithValue("@UpdatedDate", DateTime.Now);
                    sqlCommand.ExecuteNonQuery();
                }

                return Ok("Event created successfully.");
            }
            catch (Exception ex)
            {
                // Handle any errors or exceptions here
                return BadRequest("Failed to create event: " + ex.Message);
            }
        }
        [HttpPost]
        public IActionResult DeleteEvent(string title, DateTime start)
        {
            TimeZoneInfo thaiTimeZone = TimeZoneInfo.FindSystemTimeZoneById("SE Asia Standard Time");
            start = TimeZoneInfo.ConvertTimeFromUtc(start, thaiTimeZone);
            var connectionString = _configuration.GetConnectionString("DefaultConnection");
            //start = start.AddDays(1).Date;
            try
            {
                using (var connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    // Define the DELETE SQL command with a WHERE clause
                    var sqlCommand = new SqlCommand("DELETE FROM t_msd_Holiday WHERE Holiday = @Holiday AND Date = @start", connection);

                    // Add parameters for the WHERE clause
                    sqlCommand.Parameters.AddWithValue("@Holiday", title);
                    sqlCommand.Parameters.AddWithValue("@start", start);

                    // Execute the DELETE command
                    int rowsAffected = sqlCommand.ExecuteNonQuery();

                    if (rowsAffected > 0)
                    {
                        return Ok("User deleted successfully.");
                    }
                    else
                    {
                        return NotFound("User not found or deletion failed.");
                    }
                }
            }
            catch (Exception ex)
            {
                // Handle any errors or exceptions here
                return BadRequest("Failed to create event: " + ex.Message);
            }
        }
        [HttpPost]
        public IActionResult CheckUser(string username, string email)
        {
            //string _connectionString = _configuration.GetConnectionString("ConnectString_FVMySQL");
            try
            {
                using (MySqlConnection connection = new MySqlConnection(_configuration.GetValue<string>("ConnectString_MySQL:FullNameConnection")))
                {
                    connection.Open();

                    using (var cmd = new MySqlCommand("SELECT CASE WHEN COUNT(*) > 0 THEN 'yes' ELSE 'no' END AS _check FROM fv_system_users WHERE ACCOUNT = @UserId AND EMAIL = @Email", connection))
                    {
                        cmd.Parameters.AddWithValue("@UserId", username);
                        cmd.Parameters.AddWithValue("@Email", email);

                        var result = cmd.ExecuteScalar();

                        // Convert the result to a string
                        var checkResult = result != null ? result.ToString() : "no";

                        return Ok(checkResult);
                    }
                }
            }
            catch (Exception ex)
            {
                return BadRequest("Failed to create event: " + ex.Message);
            }



        }

        #endregion

        #region Report Cases Management ( Check )

        public IActionResult ReportCasesCheck(
   string bankName,
   string Filter_FromDate,
   string Filter_ToDate
   )
        {

            ViewBag.bankName = bankName;

            ViewBag.Filter_FromDate = Filter_FromDate;
            ViewBag.Filter_ToDate = Filter_ToDate;
            

            return View();
        }

       

        [HttpGet]
        public async Task<JsonResult> FetchReportCasesCheck(DateTime? fromdate, DateTime? todate, string bankName, int row = 50, int page = 1, string status = "")

        {
            if (string.IsNullOrEmpty(bankName))
            {
                return Json(new
                {
                    jsonData = new List<ReportCaseStatusModel>(),
                    currentPage = page,
                    totalPages = 0,

Views/Management/ReportCaseSummary.cshtml
@using SLA_Management.Models.ManagementModel
@using SLA_Management.Models.OperationModel
@model List<ReportCaseSummary>
@{
    ViewData["Title"] = "Report Case Summary";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var terminalList = ViewBag.CurrentTID as List<Device_info_record>;
    var selectedYear = ViewBag.SelectedYear;
    var selectedTerminalId = ViewBag.TerminalId;
}

<style>
    .btn-light {
    border: 1px solid darkgrey;
    border-radius: 10px;
}

h {
    display: flex;
    justify-content: center;
}

.chkbox {
    text-align: left;
}

.my-dropdown {
    width: 100%;
    height: 38px;
}

input:disabled {
    background-color: #f2f2f2;
}

.btnsearch {
    font-size: 18px;
}

select.form-control {
    -webkit-appearance: button;
}

input.form-control {
    -webkit-appearance: button;
    border-radius: 10px;
}


#header_search {
    top: 20px;
    position: relative;
    background-color: orange;
    border: solid;
    padding: 8px 40px 8px 40px;
    border-radius: 12px;
    font-weight: 700;
}

.item {
    padding: 0px;
}

#submit {
    display: flex;
    position: relative;
    top: 50px;
    background: lightgray;
    border: 10px double white;
    border-radius: 20px;
    padding: 0px 0px 0px 0px;
    align-content: center;
    justify-content: center;
    align-items: center;
}

#before-submit {
    display: flex;
    justify-content: center;
}

#main_search {
    margin-bottom: 50px;
    padding: 30px 0;
    margin-left: 50px;
    margin-right: 50px;
    border: 3px solid #888888;
    background-color: white;
    border-radius: 50px;
}

.dropdown-toggle {
    border-radius: 10px;
}
th,
td {
  white-space: nowrap;  
}

.issue-column {
  max-width: 250px;     
  overflow: hidden;
  text-overflow: ellipsis; 
}

th {
    text-align: center;
    vertical-align: middle;
}
td {
    padding: 0.5em !important;
    vertical-align: middle;
}

.pagination li a {
    color: black !important;
}

.boxDownload {
    background-color: rgba(255, 255, 255, 0.5);
    position: fixed;
    top: 0px;
    right: 0px;
    bottom: 0px;
    left: 0px;
    pointer-events: none;
    z-index: 10;
}

.imgDownload {
    position: sticky;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
.scroll-wrapper {
    width: 100%;
    overflow-x: auto;
}

#top-scroll {
    overflow-x: auto;
    overflow-y: hidden;
    height: 20px;
    margin-bottom: 5px;
}

#top-scroll-content {
    height: 1px;
}

#bottom-scroll {
    overflow-x: auto;
}
.custom-table {
    min-width: 1600px;
}


</style>

<div class="content contentHeader">
    <div class="container w-auto containerHeader" style="padding-bottom: 0px;">
        <div class="row">
            <div class="col col-md-1"></div>
            <div class="col col-md-11">
                <a class="text-white fs-4" id="header_search">Report Case Summary</a>
            </div>
        </div>
        <div id="main_search">
            @using (Html.BeginForm("ReportCaseSummary", "Management", FormMethod.Get, new { id = "myForm" }))
            {
                <div class="row" style="margin-top: 45px;  align-items:center; justify-content: space-around; padding:0vw 3vw; white-space:nowrap;">
                    <div class="col-md-1" style="">
                        <h>Bank : </h>
                    </div>
                    <div class="item col-md-2">
                        @Html.DropDownList("bankName", new SelectListItem[] {
                            new SelectListItem() { Text = "BAAC", Value = "BAAC", Selected = true }
                        }, new {
                            @class = "form-control dropdown",
                            @style = "border-radius: 10px;",
                            @name = "state",
                            @disabled = "disabled"
                        })
                    </div>
                    <input type="hidden" id="bankName" name="bankName" value="BAAC" />
                     <div class="col-md-1" style="">
                        
                    </div>
                    <div class="item col-md-2">
                    </div>
                     <div class="col-md-1" style="">
                        
                    </div>
                    <div class="item col-md-2">
                    </div>
                </div>

                <div class="row" style="margin-top: 30px; align-items:center; justify-content: space-around; padding:0vw 3vw; white-space:nowrap;">
                    <div class="col-md-1">
                        <h>Terminal No : </h>
                    </div>
                    <div class="item col-md-2">
                        <select class="selectpicker form-control subsearch" id="Terminal_ID" name="Terminal_ID" data-live-search="true">
                            <option data-tokens="" value="">--</option>
                            @foreach (var item in terminalList)
                            {
                                if (item.TERM_ID != selectedTerminalId)
                                {
                                    <option value="@item.TERM_ID" data-tokens="@item.TERM_ID">@item.TERM_SEQ : @item.TERM_ID : @item.TERM_NAME</option>
                                }
                                else
                                {
                                    <option value="@item.TERM_ID" data-tokens="@item.TERM_ID" selected>@item.TERM_SEQ : @item.TERM_ID : @item.TERM_NAME</option>
                                }
                            }
                        </select>
                    </div>

                    <div class="col-md-1">
                        <h>Year: </h>
                    </div>
                    <div class="item col-md-2">
                        <div class="dropdown bootstrap-select form-control subsearch">
                            <select class="form-control selectpicker subsearch" id="yearDropdown" name="year">
                                @for (int y = DateTime.Now.Year - 1; y <= DateTime.Now.Year + 5; y++)
                                    {
                                        <option value="@y" selected="@(y == selectedYear ? "selected" : null)">@y</option>
                                    }

                            </select>
                        </div>
                    </div>
                     <div class="col-md-1" style="">
                        
                    </div>
                    <div class="item col-md-2">
                    </div>
                </div>
                <div class="row" style=" align-items:center; justify-content: space-around; padding:0vw 3vw; white-space:nowrap;">
                    <div class="col-md-2">
                        <div id="submit">
                            <button type="submit" id="btnsearch" class="btn" style="padding:0px;">
                                <img src="~/images/icon_search.png" style="width: 50px; height: 50px" class="rounded-lg p-0" alt="Search" />
                            </button>

                            <a href="@Url.Action("ReportCaseSummary", "Management")" id="btnclear" class="btn" title="ล้างข้อมูล" style="padding:0px; border: 0px; background-color: transparent;">
                                <img src="~/images/icon_refresh.png" style="width: 40px; height: 40px" class="rounded-lg p-0" alt="Clear Data" />
                            </a>

                            <a title="Export to Excel" style="cursor: pointer;">
                                <img src="@Url.Content("~/images/icon_excel.png")"
                                     style="width: 50px; height: 50px;"
                                     onclick="exportTableToServer()" />
                            </a>

                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="container">
    <div class="scroll-wrapper">
        <div id="top-scroll"><div id="top-scroll-content"></div></div>
        <div id="bottom-scroll">
            <table id="summaryTable" class="table table-striped custom-table">
                <thead>
                    <tr>
                        <th class="issue-column" rowspan="2">Issue Name</th>
                        @foreach (var m in new[] { "ม.ค.", "ก.พ.", "มี.ค.", "เม.ย.", "พ.ค.", "มิ.ย.", "ก.ค.", "ส.ค.", "ก.ย.", "ต.ค.", "พ.ย.", "ธ.ค." })
                        {
                            <th colspan="2">@m</th>
                        }
                        <th colspan="2">รวม</th>
                    </tr>
                    <tr>
                        @for (int i = 0; i < 13; i++)
                        {
                            <th>4000</th><th>AService</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        foreach (var row in Model)
                        {
                            <tr>
                                <td>@row.IssueName</td>
                                @for (int i = 0; i < 12; i++)
                                {
                                    <td>@row.BaacService[i]</td>
                                    <td>@row.AService[i]</td>
                                }
                                <td>@row.TotalBaacService</td>
                                <td>@row.TotalAService</td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr><td colspan="27" style="text-align:center;">NO DATA</td></tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="boxDownload" id="boxDownload" style="display: none;">
    <img class="imgDownload" src="~/images/loading.gif">ห
</div>

<script>
    const topScroll = document.getElementById('top-scroll');
    const bottomScroll = document.getElementById('bottom-scroll');
    const topScrollContent = document.getElementById('top-scroll-content');
    const summaryTable = document.getElementById('summaryTable');

    function syncScrollbars() {
        topScrollContent.style.width = summaryTable.scrollWidth + 'px';
        topScroll.scrollLeft = bottomScroll.scrollLeft;
        topScroll.onscroll = () => bottomScroll.scrollLeft = topScroll.scrollLeft;
        bottomScroll.onscroll = () => topScroll.scrollLeft = bottomScroll.scrollLeft;
    }
    function exportTableToServer() {
        const table = document.getElementById("summaryTable");
        const rows = table.querySelectorAll("tbody tr");
        const tableData = [];

        rows.forEach(row => {
            const rowData = [];
            row.querySelectorAll("td").forEach(cell => {
                rowData.push(cell.innerText.trim());
            });
            tableData.push(rowData);
        });

        fetch('/Management/ExportFromTableReportCaseSummary', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(tableData)
        })
        .then(response => response.blob())
        .then(blob => {
            const link = document.createElement("a");
            link.href = URL.createObjectURL(blob);
            link.download = "ReportCaseSummary.xlsx";
            link.click();
        });
    }


    window.onload = syncScrollbars;
    window.onresize = syncScrollbars;
</script>